[package]
name = "ckan-rs-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
ckan-rs = { path = "../ckan-rs-lib" }
getopts = "0.2.21"
log = "0.4.17"
env_logger = "0.10.0"
reqwest = "0.11"
tokio = { version = "1.21.2", features = ["full"] }
thiserror = "1.0.40"