[package]
name = "ckan-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.144"
serde_json = "1.0.85"
bincode = "1.3"
jsonschema = "0.16.0"
reqwest = { version = "0.11", features = ["blocking"] }
flate2 = "1.0.24"
tar = "0.4.38"