[package]
name = "ckan-rs-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
ckan-rs = { path = "../ckan-rs-lib" }
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
log = "0.4.17"
env_logger = "0.10.0"
thiserror = "1.0.40"